openstack-k8s-operators/heat-operator

deploy/crds/heat.openstack.org_heats_crd.yaml
deploy/crds/heat.openstack.org_v1_heat_cr.yaml
deploy/role.yaml
deploy/role_binding.yaml
deploy/service_account.yaml
pkg/apis/heat/v1/heat_types.go
pkg/heat/dbsync.go
pkg/heat/deployment.go
tools/csv-generator.go

Right now the heat-operator user is used to create pods/jobs.
This creates a new heat user which is used to create pods/jobs.

Use heat service user to create pods/jobs

---

controllers/heat_controller.go
controllers/heatapi_controller.go
controllers/heatengine_controller.go

instead of int. This allows us to use more fine grained timeout value such as 0.1, and encodes the unit in the type itself.
Note the current version of lib-common and keystone-operator in go.mod contains the change in these dependent libraries.

Use time.Duration for timeout

---

Dockerfile
Makefile
bundle.Dockerfile
config/manifests/bases/heat-operator.clusterserviceversion.yaml
config/rbac/role.yaml
config/rbac/service_account.yaml
controllers/heat_controller.go
controllers/heatapi_controller.go
pkg/heat/const.go
templates/heatapi/config/heat-api-httpd.conf

This change corrects the Service Account name to align with other services.
In addition, it corrects the Endpoint URL to include the `%(tenant_id)s`:
From:
```
❯ openstack endpoint list --service heat -f yaml -c URL
- URL: http://heat-admin.openstack.svc:8004
- URL: http://heat-internal.openstack.svc:8004
- URL: http://heat-public-openstack.apps.okd.bne-shift.net
```
To:
```
❯ openstack endpoint list --service heat -f yaml -c URL
- URL: http://heat-admin.openstack.svc:8004/v1/%(tenant_id)s
- URL: http://heat-internal.openstack.svc:8004/v1/%(tenant_id)s
- URL: http://heat-public-openstack.apps.okd.bne-shift.net/v1/%(tenant_id)s
```

Service account

---

controllers/suite_test.go

In line with some of the other operators, this change comments out the suite_test.go content as we currently don't have things in place for envtest.

This change comments out the suite_test.go content

---

Makefile

This change is required to run the operator locally

Update makefile for seperate api module

---

config/samples/heat_v1beta1_heat.yaml
controllers/heat_controller.go

This change passes the PasswordSelectors from the base spec into the API and Engine specs. 
Additionally, this corrects an error with the samples file. It was incorrectly set as admin when it should have been service.

Pass PasswordSelectors to each service deployment

---

config/crd/kustomization.yaml

This makes sure all the CRs are registered by the common kustomize script.

Fix some CRs not being installed

---

.golangci.yaml
Makefile

The command sometimes fails because of timeout (default 1m0s) in CI. Let's increase timeout to avoid frequent failure.

Extend timeout in golangci-lint

---

api/v1beta1/heatapi_types.go
api/v1beta1/heatengine_types.go
config/crd/bases/heat.openstack.org_heatapis.yaml
config/crd/bases/heat.openstack.org_heatengines.yaml
config/crd/bases/heat.openstack.org_heats.yaml
config/samples/heat_v1beta1_heat.yaml
tests/kuttl/tests/common/assert-sample-deployment.yaml

We imported container build tools from TripleO as TCIB[1]. Now we are retiring TripleO and should complete the migration.
[1] https://github.com/openstack-k8s-operators/tcib

Replace TripleO images by TCIB images

---

templates/heat/config/heat.conf

This simplifies the heat.conf file used by services based on the following points.
- Remove the parameter descrpitons
- Remove redundant settings which configures the service default values
- Remove tuning done in TripleO mainly to support heat usage in undercloud

Simplify heat.conf

---

README.md
api/v1beta1/heat_types.go
config/crd/bases/heat.openstack.org_heatapis.yaml
config/crd/bases/heat.openstack.org_heatengines.yaml
config/crd/bases/heat.openstack.org_heats.yaml
config/samples/heat_v1beta1_heat.yaml
tests/kuttl/tests/common/assert-sample-deployment.yaml

This is used in keystone which has a separate bootstrap command, but heat does not have a bootstrap command and dbsync is the only command we have to execute during deployment.

Remove unused bootstrap debug flag

---

templates/heat/config/db-sync-config.json
templates/heat/config/heat-engine-config.json
templates/heat/config/heat.conf
templates/heat/config/heatapi-config.json

This change disable usage of log file and make all log outputs sent to stderr. The file is created inside pod and can fill up container file system.

Disable log file and use stderr for log output

---

kuttl-test.yaml
tests/kuttl/tests/basic/01-assert.yaml
tests/kuttl/tests/basic/01-deploy-heat.yaml

Instead of using install_yamls targets for deploying and cleaning up ironic, use the CR sample from config/samples. This removes a possible circular dependency issue when using install_yamls to run the jobs and to run some test steps.

Remove install_yamls dependency for kuttl tests

---

Makefile

It does not make sense to try pushing images to github.com.

Fix default IMAGE_TAG_BASE

---

tests/kuttl/tests/common/assert-sample-deployment.yaml

This was probably imported from ironic-operator but has never been implemented in heat-operator.

Remove non-existing rpcTransport spec

---

controllers/heat_controller.go

This fixes a few typos in template parameter names which are causing wrong values rendered in heat.conf.
```
$ oc describe cm/heat-config-data
...
heat.conf:
----
[DEFAULT]
region_name_for_services=regionOne
stack_user_domain_name = <no value>
stack_domain_admin = <no value>
...
```

Fix typos in template parameters

---

controllers/heatapi_controller.go
pkg/heat/const.go

keystone-operator no longer creates admin endpoint[1]. This follows that and removing admin endpoint.
[1] https://github.com/openstack-k8s-operators/keystone-operator/pull/175

Stop creating admin endpoint

---

api/v1beta1/heat_types.go
api/v1beta1/heatapi_types.go
api/v1beta1/heatengine_types.go
config/crd/bases/heat.openstack.org_heatapis.yaml
config/crd/bases/heat.openstack.org_heatengines.yaml
config/crd/bases/heat.openstack.org_heats.yaml
pkg/heat/dbsync.go
pkg/heat/initcontainer.go
pkg/heatapi/deployment.go
pkg/heatengine/deployment.go
templates/heat/bin/init.sh
templates/heat/config/heat.conf
tests/kuttl/tests/common/assert-sample-deployment.yaml

This makes the [DEFAULT] auth_encryption_key option configurable, via the global OSP secret. The secret should not be rotated once stack resources are created, otherwise users are no longer able to manipulate stacks with encrypted data.

Load secret to configure auth_encryption_key

---

controllers/heat_controller.go
controllers/heatapi_controller.go
controllers/heatengine_controller.go

Kubebuilder / operator-sdk leaves generic TODO's to provide instructions while building the operator. These aren't necessary now, so this change is cleaning up some of those generics. Specifically `TODO(user)`

Remove generic TODOs

---

controllers/heatapi_controller.go
controllers/heatengine_controller.go

Currently statuses of these CRs are not updated even after reconciler completes. This fixes that problem and ensures CRs are patched.

Ensure HeatAPI/Engine CR is patched after reconciliation

---

tests/kuttl/common/assert-sample-deployment.yaml
tests/kuttl/tests/basic/01-assert.yaml

Some fields in the assert when running the kuttl tests and are causing
them to fail. This change also modifies the directory structure of the
kuttl tests, bringing the common folder one level up, otherwise kuttl
sees it as another test case.

Amend some fields heat kuttl tests

---

controllers/heatengine_controller.go

The heat-engine controller does not manage services thus this condition is never updated.

Remove unused ExposeServiceReady condition from heat-engine

---

api/v1beta1/heat_types.go
config/crd/bases/heat.openstack.org_heatapis.yaml
config/crd/bases/heat.openstack.org_heatcfnapis.yaml
config/crd/bases/heat.openstack.org_heatengines.yaml
config/crd/bases/heat.openstack.org_heats.yaml

The first character should be upper-case to be consistent with the other keys.

Fix typo in default database Secret key

---

.github/workflows/golangci-lint.yaml

We will run the test target in Prow as defined by this PR: https://github.com/openshift/release/pull/39453
Thus it is not necessary to duplicate this test execution in Github actions here.

Remove makefile test target from Github action

---

api/v1beta1/heat_types.go
api/v1beta1/heatapi_types.go
api/v1beta1/heatcfnapi_types.go
config/crd/bases/heat.openstack.org_heatapis.yaml
config/crd/bases/heat.openstack.org_heatcfnapis.yaml
config/crd/bases/heat.openstack.org_heats.yaml

... because the field contains multiple endpoints(heat-api and heat-api-cfn, internal and public)

Rename spec.APIEndpoint to plural

---

config/samples/heat_v1beta1_heat.yaml

Some spec keys of sub CRs(eg. HeatAPI) are overridden by the same keys of the Heat CR, so defining these keys has no effect.

Remove spec keys copied from Heat CR

---

api/v1beta1/heat_types.go
config/crd/bases/heat.openstack.org_heats.yaml
tests/functional/heat_controller_test.go

This status is not used because we use ones specific to sub resources such as heatAPIReadyCount.

Remove unused readyCount from Heat CR

---

api/v1beta1/heat_types.go
api/v1beta1/heatapi_types.go
api/v1beta1/heatengine_types.go
controllers/heat_controller.go
controllers/heatapi_controller.go
controllers/heatengine_controller.go

This ensures the Ready Condition is reset when CR becomes once ready but something fails during reconfiguration.

Reset Ready condition when update failed

---

controllers/heatapi_controller.go
controllers/heatcfnapi_controller.go

This makes sure that the conditions describing status of keystone resource creation are initialized.

Make sure conditions for keystone resources are initialized

---

api/v1beta1/heat_types.go
api/v1beta1/heatapi_types.go
api/v1beta1/heatcfnapi_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/heat.openstack.org_heatapis.yaml
config/crd/bases/heat.openstack.org_heatcfnapis.yaml
config/crd/bases/heat.openstack.org_heats.yaml
controllers/heat_controller.go
controllers/heatapi_controller.go
controllers/heatcfnapi_controller.go
tests/functional/heat_controller_test.go

These items presented in CR status are not really used. Endpoints can be discovered using Keystone and we have no use case to require service id.

Remove endpoint url and keystone service id from status

---

config/samples/heat_v1beta1_heat.yaml

These keys are required because we inherit definition of sub CRs. Currently this does not appear as a problem because webhook is modifying the value, but we should fix that behavior ideally and then the problem appears
This adds the keys back until we determine how we handle spec keys inherited from top-level CR.

Add back secret keys for sub CRs

---

api/v1beta1/heatcfnapi_types.go

We updated the logic in HeatAPI and HeatEngine by [1] but HeatCfnAPI was not covered by that change.
[1] f3a97a1678dd585c73b6453e5e3c539084f22ce3

Use ready condition to determine readiness of HeatCfnAPi

---

api/v1beta1/heat_types.go
api/v1beta1/heatapi_types.go
api/v1beta1/heatcfnapi_types.go
api/v1beta1/heatengine_types.go
config/crd/bases/heat.openstack.org_heatapis.yaml
config/crd/bases/heat.openstack.org_heatcfnapis.yaml
config/crd/bases/heat.openstack.org_heatengines.yaml
config/crd/bases/heat.openstack.org_heats.yaml

Allows `Ready` condition status to be display at the CLI via `oc get heat`, `oc get heatapi`, etc, similar to what we do for other operators.

Display status in CLI

---

pkg/heat/dbsync.go

The heat-manage command should be executed at a node with heat-engine, instead of heat-api.

Use heat-engine image to run db sync

---

controllers/heatcfnapi_controller.go

We should use the different selector for Cfn API.

HeatCfnAPI: Fix component selector

---

tests/functional/base_test.go

The spec key has been hidden since we refactored Heat CR definition using templates.

envtest: Remove spec.secret from sub CRs

---

api/v1beta1/common_types.go
config/crd/bases/heat.openstack.org_heats.yaml

This spec is not used, because the value is determined by underlying mariadb operator. The spec is required in sub CRs.

Remove spec.databaseHostname from Heat CR

---

api/v1beta1/common_types.go
config/crd/bases/heat.openstack.org_heatapis.yaml
config/crd/bases/heat.openstack.org_heatcfnapis.yaml
config/crd/bases/heat.openstack.org_heatengines.yaml
config/crd/bases/heat.openstack.org_heats.yaml

Currently we define defaults in two layers but this is redundant.

Remove redundant default of PasswordSelectors

---

api/v1beta1/common_types.go
config/crd/bases/heat.openstack.org_heatapis.yaml
config/crd/bases/heat.openstack.org_heatcfnapis.yaml
config/crd/bases/heat.openstack.org_heatengines.yaml
config/crd/bases/heat.openstack.org_heats.yaml

Some parameter descriptions specifically mention API but these are used by not only API but the other services.

Fix common parameter descriptions

---

tests/functional/base_test.go
tests/functional/heat_controller_test.go

Our base_test.go file has a helper function to create the Heat passwords secret. This change removes duplicate declarations of this secret from the heat_controller_test.go file and replaced them with the helper function.

Remove duplicate secret declaration from tests

---

config/rbac/role.yaml
controllers/heat_controller.go
controllers/heatapi_controller.go
controllers/heatcfnapi_controller.go
controllers/heatengine_controller.go

This fixes a few missing/necessary rbac rules as well as ownership defined, according to the resources actually created by each controller.

Fix some wrong/missing ownership references

---

tests/functional/base_test.go
tests/functional/heat_controller_test.go

Some functions we implement in our own test helpers are already implemented in the common test helper module in lib-common. Let's use the common implementations to reduce duplicated implementations.

Drop functions already implemented in test helper

---

tests/kuttl/common/assert-sample-deployment.yaml

We haven't been running kuttl tests in CI and haven't caught some problems.
This fixes the existing failures so that we can enable the tests now.

Fix kuttl tests

---

api/v1beta1/conditions.go
controllers/heat_controller.go
tests/functional/heat_controller_test.go

This introduces the new HeatStackDomainCondition so that users can observe status of heat stack doamin creation process. Currently failures at that step are not exposed via status and users have to check pod log to find out why the creation is not progressing.

Add new condition for stack domain creation

---

Makefile

Now ginkgo is commonly used by the other operators. Let's switch to it so that we use the consistent test execution framework.
This fixes the missing definition of GINKGO parameter.

Replace go test by ginkgo

---

controllers/heat_controller.go

This ensures the controller watches service account, role, and role bindings to reconcile these resources in case any change is made.

Watch RBAC resources to trigger reconcile

---

tests/functional/suite_test.go

... to avoid executing tests with webhook not fully initialized.

Ensure webhook is ready before starting functional tests

---

kuttl-test.yaml

... following the current usage in other operators (eg. keystone).

Add back namespace name for kuttl config file

---

config/manifests/bases/heat-operator.clusterserviceversion.yaml

This should hide the heat package/bundle in the OpenShift console as we only want the main OpenStack operator to show up there.

CSV: Set operator-type: non-standalone

---

controllers/heat_controller.go
controllers/heatapi_controller.go
controllers/heatcfnapi_controller.go

Currently the top-level ready condition does never become true for HeatCfnAPI, because the logic to update the condition has not been properly updated.

Fix ready condition handling for HeatCfnAPI

---

api/v1beta1/common_types.go
api/v1beta1/zz_generated.deepcopy.go
config/samples/heat_v1beta1_heat.yaml
pkg/heatapi/deployment.go
pkg/heatcfnapi/deployment.go
pkg/heatengine/deployment.go
tests/functional/base_test.go
tests/functional/heat_controller_test.go

Currently the default value are ignored because these specs are set to 0 by webhook. Update the type from `int32` to `*int32` to avoid that behavior and ensure the expected default values are used.

Fix defaulting of Replicas spec

---

Makefile

This is a follow-up of the previous change which replaces go test by ginkgo and fixes the missing PROC_CMD variable so that all tests are executed concurrently.

Run tests concurrently

---

Makefile
api/bases/heat.openstack.org_heatapis.yaml
api/bases/heat.openstack.org_heatcfnapis.yaml
api/bases/heat.openstack.org_heatengines.yaml
api/bases/heat.openstack.org_heats.yaml

With the new api sub module, consumer operators just have to import the api submodule. For envtest it is required to install CRD for e.g. keystone-operator and mariadb-operator to be able to use it.
Moving the directory config/crd/bases which holds the generated files in to the api module that they are available with the module and link the dir in the original place does not work as kustomize autodetect fails on symlinked directories [1].
This updates the `generate` Makefile target to copy config/crd/bases to /api on successful generation run.

Copy rendered CRD files dir to /api/bases in make manifests

---

api/v1beta1/conditions.go
controllers/heat_controller.go
tests/functional/heat_controller_test.go

We have added the common RabbitMqTransportURLReady to lib-common to reduce duplicate implementations.
Depends-on: https://github.com/openstack-k8s-operators/lib-common/pull/300

Replace HeatRabbitMqTransportURLReady by common condition

---

api/go.mod
go.mod

It seems these were caused by a bug in old renovate we used.

Remove duplicate indirect in go.mod

---

README.md
api/bases/heat.openstack.org_heatapis.yaml
api/bases/heat.openstack.org_heatcfnapis.yaml
api/bases/heat.openstack.org_heatengines.yaml
api/bases/heat.openstack.org_heats.yaml
api/v1beta1/common_types.go
api/v1beta1/heat_types.go
config/crd/bases/heat.openstack.org_heatapis.yaml
config/crd/bases/heat.openstack.org_heatcfnapis.yaml
config/crd/bases/heat.openstack.org_heatengines.yaml
config/crd/bases/heat.openstack.org_heats.yaml
config/samples/heat_v1beta1_heat.yaml
tests/kuttl/common/assert-sample-deployment.yaml

... so that we can check behavior of heat services more closely in CI. This also removes the default value for customServiceConfig following the other operators.

Enable debug log for heat services

---

controllers/heat_controller.go
controllers/heatapi_controller.go
controllers/heatcfnapi_controller.go
controllers/heatengine_controller.go

If we're returning from a if statement, we really don't need an else. These can be simplified and made more legible by simply removing the else and having a seperate if block.
This is really just a quality of life patch. IMO, the use of `else` can often make code a bit harder to follow and read. 
If this is just something we're doing for consistency with the wider org's sake, I'm happy to raise it to the wider group for broader perspective. But at least here, I think it makes things a little nicer to read and follow.

Simplify if else statements

---

controllers/heat_controller.go
controllers/heatapi_controller.go
controllers/heatcfnapi_controller.go
controllers/heatengine_controller.go

Currently, we still have a mix of time.Duration and time.Second. This change replaces the remaining time.Duration instances with time.Second * n.

Use consistent method for setting time.Second * n

---

pkg/heatapi/deployment.go
pkg/heatcfnapi/deployment.go
pkg/heatengine/deployment.go
templates/heat/config/heat-api-httpd.conf
templates/heat/config/heat-cfnapi-httpd.conf

This option is not really used because we have WsgiScriptAlias which directs access under / to the script.

Remove unnecessary DocumentRoot for apache

---

README.md
api/bases/heat.openstack.org_heats.yaml
api/v1beta1/heat_types.go
config/crd/bases/heat.openstack.org_heats.yaml
config/rbac/role.yaml
controllers/heat_controller.go
go.mod
main.go
templates/heat/config/heat.conf
tests/functional/heat_controller_test.go
tests/functional/suite_test.go
tests/kuttl/common/assert-sample-deployment.yaml

This introduces the capability to use memcached as cache backend, to reproduce the setting in TripleO.
Enabling caching in heat provides large performance benefit in token validation and some resource queries.

Enable caching using memcached

---

.github/create_bundle.sh
api/v1beta1/heat_types.go
config/default/manager_default_images.yaml
config/manifests/bases/heat-operator.clusterserviceversion.yaml
tests/kuttl/common/assert-sample-deployment.yaml

This PR adds support for installing the operator in disconnected network environments. To build with image-digests set USE_IMAGE_DIGESTS=true before running make bundle.
For Prow jobs we are enabling this via .prow-ci.env
This drops the old logic from create_bundle.sh which has been broken with operator-sdk's make bundle for some time.
(NOTE: this currently requires a secure registry)
Jira: [OSP-26486](https://issues.redhat.com//browse/OSP-26486)

Support disconnected network environments

---

.prow_ci.env
tests/kuttl/common/assert-sample-deployment.yaml

This is used to enable USE_IMAGE_DIGESTS for prow builds

Add .prow_ci.env

---

controllers/heat_controller.go
go.mod
go.sum

The lib-common/modules/database is moved to mariadb-operator/api to remove a circular dependency.

Use database helpers from mariadb-operator/api

---

tests/functional/heat_controller_test.go

Ths pointer library[1] has been deprecated and replaced by ptr. This change refactors the usage on the new library[2] and usage.
[1] https://pkg.go.dev/k8s.io/utils/pointer
[2] https://pkg.go.dev/k8s.io/utils/ptr

Replace deprecated pointer library.

---

config/manifests/bases/heat-operator.clusterserviceversion.yaml

Update to use new 'features.operators.openshift.io' annotations format for disconnected support
Jira: [OSP-30201](https://issues.redhat.com//browse/OSP-30201)

required infra annotations for OCP 4.14+

---

controllers/heat_controller.go
templates/heat/config/heat.conf
tests/functional/heat_controller_test.go

This change updates the heat.conf file to ensure our connections to Keystone happen via the internal endpoint rather than the public one.

Use internal Keystone endpoint

---

config/samples/heat_v1beta1_heatapi.yaml
config/samples/heat_v1beta1_heatapicfn.yaml
config/samples/heat_v1beta1_heatengine.yaml
config/samples/kustomization.yaml

Fixes the following bundle validation warnings by adding samples of these internal APIs:
WARN[0000] Warning: Value heat.openstack.org/v1beta1, Kind=HeatAPI: provided API should have an example annotation
WARN[0000] Warning: Value heat.openstack.org/v1beta1, Kind=HeatCfnAPI: provided API should have an example annotation
WARN[0000] Warning: Value heat.openstack.org/v1beta1, Kind=HeatEngine: provided API should have an example annotation

Fix bundle validations

---

Makefile

This change adds a env var to configure the OPERATOR_SDK_VERSION in-line with the other operators from the OKO project.

Add operators-sdk-version to makefile

---

Makefile

This is the required Makefile entries and additional tweaks needed to use operator-sdk from local bin
add operator-sdk target to fetch to local bin
update bundle to use OPERATOR-SDK var

update Makefile for local operator-sdk

---

Makefile

copy some of the Makefile improvements from operator-sdk init skeleton base on v1.31.0

standardize Makefile operator-sdk local

---

.prow_ci.env
Dockerfile
Makefile

This change ensures the heat-operator is built with FIPS compliance.

This change adds requirements for FIPS

---

controllers/heat_controller.go
controllers/heatapi_controller.go
controllers/heatcfnapi_controller.go
controllers/heatengine_controller.go
pkg/heat/volumes.go
templates/heat/bin/init.sh
tests/functional/heat_controller_test.go
tests/kuttl/tests/heat_tls/01-assert.yaml

The my.cnf file gets added to the secret holding the service configs. The content of my.cnf is centrally managed in the mariadb-operator and retrieved calling db.GetDatabaseClientConfig(tlsCfg)
Depends-On: https://github.com/openstack-k8s-operators/mariadb-operator/pull/190
Depends-On: https://github.com/openstack-k8s-operators/mariadb-operator/pull/191
Jira: [OSPRH-4547](https://issues.redhat.com//browse/OSPRH-4547)

[tlse] TLS database connection

---

api/v1beta1/heat_webhook.go

Nothing to validate here yet but lets add this function to make it clear this is where OpenStackControlplane will call to validate things.

Add HeatSpecCore default for future validations

---

controllers/heat_controller.go
pkg/heat/const.go

This change adds the heat_stack_user role during the initial reconcile. It is used as per:
https://docs.openstack.org/heat/2023.2/admin/stack-domain-users.html\#usage-workflow

Create heat_stack_user role during reconcile

---

Makefile
controllers/heat_controller.go
controllers/heatapi_controller.go
controllers/heatcfnapi_controller.go
controllers/heatengine_controller.go
go.mod
go.sum
pkg/heat/const.go
tests/functional/heat_controller_test.go

This change refactors the use of all GetDatabaseByName() calls to use the new GetDatabaseByNameAndAccount() helper function.
this can either supersede #339 or be merged into #339.

Refactor getdatabase use

---

controllers/heatengine_controller.go

The label is incorrectly set to: "component: api"

Change heat engine pod label

---

controllers/heatcfnapi_controller.go

The previous patch missed the check of `AllSubConditionIsTrue` that, has a consequence, marks the global `ReadyCondition` as `True`. This patch fixes the wrong behavior adding the missing code block.

Fix HeatCnfAPI ReadyCondition check

---

controllers/heat_controller.go
controllers/heatapi_controller.go
controllers/heatcfnapi_controller.go
controllers/heatengine_controller.go

This patch represents a follow up of the current `observedGeneration` work and the idea is to check that field in the sub resources and mirror the `Condition` (as well as `ReadyCount`) only when the generation is the last seen.
It represents a follow up of #345.

Check the ObservedGeneration for the generated subCRs

---

controllers/heat_controller.go
controllers/heatapi_controller.go
controllers/heatcfnapi_controller.go
controllers/heatengine_controller.go

To make it easier to reason about when the instance is updated this
patch removes the explicit status update form the reconcile
code path and let the controller rely on the deferred PatchInstance call
as the only place where the instance is persisted.
The removed code probably didn't cause any trouble as it only updated
the status subresource and all the non status update (the self finalizer)
is guarded with an explicit return from the reconciler. So no non status
update is lost due to this status update. Still this cleanup might help
avoiding future issues.

Remove explicit status update

---

.pre-commit-config.yaml
controllers/heat_controller.go
controllers/heatapi_controller.go
controllers/heatcfnapi_controller.go
controllers/heatengine_controller.go
tests/functional/base_test.go
tests/functional/heat_controller_test.go
tests/functional/heat_webhook_test.go
tests/functional/suite_test.go

* removed unused func params
* ignore revive dot-imports rule on ginkgo and gomega as dot import
there is the recommended practice
* various small style fixes found by the linter

Ensure golangci-lint runs on all files

---

api/go.mod
api/go.sum
api/v1beta1/heat_webhook.go
go.mod
go.sum
tests/functional/heat_webhook_test.go

Can also be called from the openstack-operator webhook on the HeatSpecCore, like for other operators in [1].
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/505
[1] https://github.com/openstack-k8s-operators/openstack-operator/blob/d2703d3a321c979dacaca95b5d4a634bf116e0db/apis/core/v1beta1/openstackcontrolplane_webhook.go#L181

Add webhook to validate service override endpoint type

---

templates/heat/config/heat.conf

Enable causality checks for read operations to avoid random db issues like Deadlock and IntegrityError as we're using multi-master galera cluster.

Enable causality checks for db operations

---

api/v1beta1/heat_types.go
api/v1beta1/heat_webhook.go
tests/functional/heat_webhook_test.go

This change allows for the ValidateUpdate() webhook to be bypassed. This provides functionality for advanced use cases where the user has independently validated that their update won't break the deployment, or orphan any data in an old database.
It's anticipated that this functionality will be required in cases where we deploy the control plane and point it at an existing database. Then perform a database migration, in which case we want to redirect the Heat deployment to the new database.
Since this operation is inherently dangerous. By default, this is an undocumented feature that is intended to facilitate situations where users are confident in the operation they are performing.

Bypass validate update

---

api/bases/heat.openstack.org_heats.yaml
api/v1beta1/heat_types.go
config/crd/bases/heat.openstack.org_heats.yaml

Else it would be initialized to empty string when created with empty template and then webhook would not allow it to be modified.

Add default for DatabaseInstance

---

templates/heat/config/heat.conf

This patch enables Secure RBAC to use Keystone default roles and Keystone scoped tokens.

Enable Secure RBAC

---

templates/heat/bin/init.sh

If a user tries to provide a auth_encryption_key containing spaces, the current implementation will only apply up until the first space. This will result in heat-engine failing to start because the encryption_key is not 32 characters or longer.

Handle spaces in encryption key

---

controllers/heat_controller.go
controllers/heatapi_controller.go
controllers/heatcfnapi_controller.go
controllers/heatengine_controller.go

Currently the reconciler returned both a non-zero result and a non-nil error.
The result will always be ignored if the error is non-nil and the non-nil error causes reqeueuing with exponential backoff.
In case of NotFound return nil that the ReqeueAfter is used.
For more details, see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler

Return nil error in case NotFound and to use RequeueAfter

---

api/v1beta1/heat_webhook.go
tests/functional/heat_webhook_test.go

We added a webhook validation for the HeatSpecCore struct in: https://github.com/openstack-k8s-operators/heat-operator/pull/407
However, we also need the same validation added to the HeatSpec ValidateUpdate function. This change adds the missing validation, along with a functional test to verify it works.

Add functional tests and HeatSpec webhook validation

---

.gitignore
controllers/heat_controller.go
controllers/heatapi_controller.go
controllers/heatcfnapi_controller.go
controllers/heatengine_controller.go

variables and comments were misleading, as we are creating secrets instead of configmaps

Replace configmap references with secret

---

api/v1beta1/heat_types.go
api/v1beta1/heatapi_types.go
api/v1beta1/heatcfnapi_types.go
api/v1beta1/heatengine_types.go
controllers/heat_controller.go
controllers/heatapi_controller.go
controllers/heatcfnapi_controller.go
controllers/heatengine_controller.go

This change does some tidy up of how we handle conditions. It deduplicates the code that determines if we're initializing or copy conditions and seperates logic into distinct functions

Tidy up condition handling

---

Makefile
controllers/heat_controller.go
controllers/heat_controller_test.go
tests/functional/heat_controller_test.go

This change refactors the generateServiceSecrets function to deduplicate code and move logic related to vhosts and templateParameters into dedicated functions.

Refacter service secrets function

---

ci/tempest/ci_fw_vars.yaml
ci/tempest/control_plane_hook.yaml
zuul.d/jobs.yaml
zuul.d/project.yaml

https://logserver.rdoproject.org/27/427/92f3a196c16ad9deba0d9e1852496f914ab4ec89/github-check/heat-operator-tempest-multinode/0ad5969/controller/ci-framework-data/tests/test_operator/tempest-tests/stestr_results.html

Add zuul tempest jobs

---

controllers/heat_controller.go
tests/functional/base_test.go
tests/functional/heat_controller_test.go

If a user provides a AuthEncryptionKey less than 32 characters, the Heat service will fail to start and pods will CrashLoopBackOff. This change validates the length of the provided value to ensure we can return an error early rather than waiting until the service is trying to initialize.
Jira: https://issues.redhat.com/browse/OSPRH-10506

Validate AuthEncryptionKey length

---

controllers/heat_controller.go
controllers/heatapi_controller.go
controllers/heatcfnapi_controller.go
controllers/heatengine_controller.go

It is hidden right now if there is an error in configured named fields and index. Lets log the error and return the current state of requests.
With this the findObjectsForSrc() will exit with an hidden error like:
```
"error": "Index with name field:.spec.ksmTls.caBundleSecretName does not exist"
```

Make sure to log error in findObjectsForSrc()

---

controllers/heat_controller.go

This may result in a project scoped token issued that can't create projects in the domain i.e only a domain scoped token can create projects in the domain.

Don't create stack_domain_admin user with project

---

api/bases/heat.openstack.org_heatapis.yaml
api/bases/heat.openstack.org_heatcfnapis.yaml
api/bases/heat.openstack.org_heatengines.yaml
api/bases/heat.openstack.org_heats.yaml
api/v1beta1/common_types.go
config/crd/bases/heat.openstack.org_heatapis.yaml
config/crd/bases/heat.openstack.org_heatcfnapis.yaml
config/crd/bases/heat.openstack.org_heatengines.yaml
config/crd/bases/heat.openstack.org_heats.yaml
controllers/heat_controller.go
templates/heat/config/00-default.conf
tests/kuttl/common/assert-sample-deployment.yaml

This is different in OSP 17.1 environments and we can't assume it to be the same as service password.
jira: https://issues.redhat.com/browse/OSPRH-10914

Add HeatStackDomainAdminPassword to heat passwords

---

controllers/heat_controller.go
controllers/heatapi_controller.go
controllers/heatcfnapi_controller.go
controllers/heatengine_controller.go

This change ensures the customServiceConfigSecrets value is indexed for when we need to use it in the FindObjectsForSrc function

Index the customServiceConfigSecrets for use in the Secret lookup

---

api/go.mod
api/go.sum
api/v1beta1/heatapi_types.go
api/v1beta1/heatcfnapi_types.go
controllers/heatapi_controller.go
controllers/heatcfnapi_controller.go
go.mod
go.sum

The current ExposeServiceReadyCondition can be confusing since it just reflects if the k8s service got created, but not the route to expose the public endpoint. This changes to a new CreateServiceReadyCondition to prevent this.
Jira: [OSPRH-4164](https://issues.redhat.com//browse/OSPRH-4164)
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/572

Switch to use new CreateServiceReadyCondition

---

api/bases/heat.openstack.org_heats.yaml
api/v1beta1/heat_types.go
api/v1beta1/heat_webhook.go
config/crd/bases/heat.openstack.org_heats.yaml
controllers/heat_controller.go
templates/heat/config/heat-api-httpd.conf
templates/heat/config/heat-cfnapi-httpd.conf

This patch adds an apiTimeout field to the HeatSpecBase to allow human operators to simultaneously configure the timeouts for HAProxy, Apache, and the rpc_response_timeout.
The apiTimeout defaults to 60 seconds, to mimic the behavior present in OSP17.
Having different timeouts for HAProxy, Apache, and rpc_response_timeout is possible setting the HAProxy timeout in the apiOverride, the Apache timeout with apiTimeout, and setting rpc_response_timeout in the top level Heat customServiceConfig.
To be able to change the HAProxy value based on the apiTimeout with any update (and not just the first time) the code adds a custom annotation "api.heat.openstack.org/timeout" with the value that was initially set, this way flags it as being set by the heat-operator.
closes …

Add configurable API Timeouts

---

zuul.d/jobs.yaml

This change adds specific tempest tests that are known to not work upstream. Some issues for example include the lack of valid DNS server and the dependency on DNS to work with TLS endpoints that are enabled by default.

Skip Heat tempest tests with known issues upstream

---

api/v1beta1/common_types.go
api/v1beta1/heat_types.go
api/v1beta1/zz_generated.deepcopy.go
controllers/heat_controller.go
pkg/heat/dbsync.go
pkg/heatapi/deployment.go
pkg/heatcfnapi/deployment.go
pkg/heatengine/deployment.go
tests/functional/heat_controller_test.go

nodeSelectors are not currently applied consistently across all operators.
Some do not support nodeSelectors at all - will be implemented in this series of pull requests.
Some do not apply them to every pod (jobs/cronjobs esp) - will be resolved in this series of pull requests.
Some do not apply a node selector update correctly, only when not initially set.
Some support nodeSelectors but do not inherit the default nodeSelector from the OpenstackControlPlane CR.
Jira: [OSPRH-10734](https://issues.redhat.com//browse/OSPRH-10734)

Ensure nodeSelector logic is consistent for all operators

---

templates/heat/config/00-default.conf

Whenever one of the mecached pods disappears, because of a rolling restart during a minor update or as result of a failure, APIs can take a long time to detect that the pod went away and keep trying to reconnect.
From a quick round of tests we saw downtimes up to ~150s.
By enabling the retry_client and limiting the number of retries the behavior seems much more acceptable.
Similarly, when TLS is not in use, we may want to set a lower value for memcache_dead_retry so to eventually reconnect to a new pod (having the same dns name but different ip) much faster.
Jira: https://issues.redhat.com/browse/OSPRH-11935

Configure dogpile.cache to deal with memcached pods failures

---

zuul.d/jobs.yaml

Changed var name to match the changes in this patch: https://github.com/openstack-k8s-operators/ci-framework/pull/2374/commits

Change test var name to match changes in cifmw

---

controllers/heatapi_controller.go
controllers/heatcfnapi_controller.go
controllers/heatengine_controller.go

We trigger reconciles for each controllers based on different events. This can lead to a situation where Heat engine - which doesn't have the same number of events that will trigger a reconcile, becomes out of sync with the other controllers. For example, the configs which are essentially the same but updated with https endpoints can be synced by the HeatAPI and HeatCfnApi controllers first, before the HeatEngine controller finally catches up. In this interval of time the heat-engine process will fail since it's trying to speak to non https endpoints instead of the correct https ones.
Jira: https://issues.redhat.com/browse/OSPCIX-795

Make sure we reconcile heat-engine secrets

---

templates/heat/config/00-default.conf
tests/functional/heat_controller_test.go

In HA tests it was identified that pymemcache backend does not recover/fail over to the next memcache instance when one goes away unexpected. Using memcache_pool with bmemcache does failover properly.
The memcache_sasl_enable=true is a workaround to force oslo.cache to switch to the bmemcache driver, which is the only driver in memcache_pool supporting tls+fips.
Jira: [OSPRH-16651](https://issues.redhat.com//browse/OSPRH-16651)
Co-outhored-by: Luca Miccini <lmiccini@redhat.com>

Change memcache to use memcache_pool driver

---

templates/heat/config/00-default.conf

Since https://review.opendev.org/c/openstack/oslo.cache/+/949978 is merged and backported to all the stable releases let's remove the workaround.
Patch was also cherry-picked to downstream antelope.
Jira: https://issues.redhat.com/browse/OSPRH-17029

Remove memcached_sasl_enabled=True workaround
