- build/Dockerfile.rhel
update to latest style
Use registry.redhat.io for base ubi
use ARGs for most upstream vs downstream differences
> Update to latest style for Dockerfile.rhel

- .pull_request_pipeline
- .travis.yml
- pkg/controller/heat/heat_controller.go
- pkg/heat/deployment.go
- version/version.go
> Add .travis.yml to enable lint and unit tests

- .github/create_bundle.sh
- .github/create_opm_index.sh
- .github/dependabot.yml
- .github/workflows/build-horizon-operator.yaml
- .github/workflows/golangci-lint.yaml
- .github/workflows/label-on-pr.yaml
- .github/workflows/pull_request_workflow.yml
- .github/workflows/release-horizon-operator.yaml
- go.mod
This introduces tools as well as definitions to run basic CI jobs following the other operators.
> Add basic CI tools

- Dockerfile
- Makefile
- bundle.Dockerfile
- config/manifests/bases/heat-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- config/rbac/service_account.yaml
- controllers/heat_controller.go
- templates/heatapi/config/heat-api-httpd.conf
This is a large PR with multiple changes to add the required changes to RBAC and the Dockerfile.
> Add required changes for compliance with overall project

- OWNERS
- OWNERS_ALIASES
More about aliases file at [1]
[1] https://git.k8s.io/community/contributors/guide/owners.md#owners_aliases
> Adding aliases files and adding more members.

- config/rbac/role.yaml
- controllers/heat_controller.go
- controllers/heatapi_controller.go
- controllers/heatengine_controller.go
This is the first attempt to add required rbac rules to individual operators so that operators can manipulate the resources. Note that this is not yet tested completely so there might be some more rules we have to add later, but we can fix apparently missing rules now to (hopefully) make the later attempt easier.
> Fix missing RBAC rules

- Makefile
- api/go.mod
- api/go.sum
- renovate.json
This is need for renovate to generate proper version bump PRs.
> [renovate] run go mod tidy for both mod files

- README.md
- api/v1beta1/heat_types.go
- api/v1beta1/heatapi_types.go
- api/v1beta1/heatengine_types.go
- config/crd/bases/heat.openstack.org_heatapis.yaml
- config/crd/bases/heat.openstack.org_heatengines.yaml
- config/crd/bases/heat.openstack.org_heats.yaml
- config/samples/heat_v1beta1_heat.yaml
- tests/kuttl/tests/common/assert-sample-deployment.yaml
... instead of using AdminPassword.
> Use specific secret keys by default

- controllers/heat_controller.go
- controllers/heatapi_controller.go
Golang errors should be wrapped in return statements to make life easier while troubleshooting where errors are coming from. This change adds fmt.Errorf() wrapping to each error along with a more meaningful error message for each.
> Wrap errors when returning them

- controllers/heat_controller.go
- controllers/heatapi_controller.go
This reverts commit 1e86ec68fb2cbaecc81093b78121ea994e0e21cc.
> Revert "Wrap errors when returning them"

- README.md
We already replaced TripleO images by TCIB images.
> Replace remaining references to TripleO images

- controllers/heat_controller.go
- controllers/heatapi_controller.go
- controllers/heatcfnapi_controller.go
- controllers/heatengine_controller.go
... according to the latest implementations in the other operators.
> Refactor Reconcile function

- controllers/heat_controller.go
The returned values do not change even if we remove these if blocks.
> Remove redundant if blocks

- controllers/heat_controller.go
This refactors and renames functions to manage stack domain resources, to make the interface more consistent and explicit.
> Refactor functions to ensure stack domain resources

- controllers/heat_controller.go
Move OpenStack API related tasks to their own dedicated function
> Refactor reconcileNormal

- controllers/heat_controller.go
Move the keystoneAPI variable to heap for re-use across functions. Once we look it up the first time in `generateServiceConfigMaps`, we don't need to do it again the next time it is required in `ensureStackDomain`
> Keystone api global

- pkg/heat/dbsync.go
... instead of hard-coding the string value.
> Use constant to define restart policy

- controllers/heatapi_controller.go
- controllers/heatcfnapi_controller.go
- controllers/heatengine_controller.go
- pkg/heat/const.go
... instead of re-defining the same.
> Use ComponentSelector in lib-common

- controllers/heatapi_controller.go
- controllers/heatcfnapi_controller.go
ReconcileInit is not completed at these steps.
> Remove wrong messages to announce completion of init

- Makefile
- api/v1beta1/common_types.go
- api/v1beta1/heat_types.go
- config/crd/bases/heat.openstack.org_heatapis.yaml
- config/crd/bases/heat.openstack.org_heatcfnapis.yaml
- config/crd/bases/heat.openstack.org_heatengines.yaml
- config/crd/bases/heat.openstack.org_heats.yaml
... to mainly catch the usage with both omitempty tag and default value, which can cause unexpected behavior[1].
[1] https://github.com/gibizer/operator-lint/tree/main/linters/crd/C003
> Bump operator-lint version

- README.md
Some of the interfaces have been changed since this documentation was last updated. This change brings the documentation into consistency with the current state of the operator.
> Update docs to represent current state

- controllers/heatapi_controller.go
We should use the correct message, not the one for InputReadyCondition.
> Fix wrong message used for ExposeServiceReadyCondition

- controllers/heat_controller.go
- tests/functional/heat_controller_test.go
This updates env tests so that we validate every single resource step in operator and assert conditions.
> Test step-by-step condition transition in env tests

- tests/functional/base_test.go
There are some more functions already implemented in lib-common. This replaces the remaining ones.
> Use (more) functions from TestHelper

- tests/functional/heat_controller_test.go
- tests/functional/suite_test.go
... to reduce the duplicated logic.
> Use the common func to manage TransportURL Secret

- api/go.mod
- api/go.sum
- go.mod
- go.sum
- tests/functional/heat_controller_test.go
Depends-on: https://github.com/openstack-k8s-operators/lib-common/pull/294
> Use new helper function to ensure CM is not created

- main.go
- tests/functional/suite_test.go
This ensures webhook is started when controller-manage deployment becomes ready.
> Ensure webhook is started

- controllers/heat_controller.go
- go.mod
- go.sum
This fixes the wrong domain(default) used where the domain admin user is created.
> Create heat_stack_domain_admin user in heat_stack domain

- controllers/heat_controller.go
We have multiple functions but each of these is tiny. Squashing these into a single function saves us from passing multiple instances to each layer.
Also this removes redundant lookup of the global secret.
> Refactor creation of heat stack domain

- api/bases/heat.openstack.org_heatapis.yaml
- api/bases/heat.openstack.org_heatcfnapis.yaml
- api/bases/heat.openstack.org_heatengines.yaml
- api/v1beta1/heatapi_types.go
- api/v1beta1/heatcfnapi_types.go
- api/v1beta1/heatengine_types.go
- config/crd/bases/heat.openstack.org_heatapis.yaml
- config/crd/bases/heat.openstack.org_heatcfnapis.yaml
- config/crd/bases/heat.openstack.org_heatengines.yaml
... because these are required to deploy services properly.
> Make DatabaseHostname and TransportURLSecret required

- go.mod
- go.sum
... so that we use the released version number consistently.
> Fix lib-common/modules/database version

- config/manifests/bases/heat-operator.clusterserviceversion.yaml
We should have added this when we introduced that CR.
> Fix missing HeatCfnAPI CR in csv

- api/v1beta1/heat_webhook.go
- tests/functional/heat_webhook_test.go
We currently have no mechanism to validate the new database will match the existing database. This could ultimatly result in user objects being orphaned and unrecoverable. We may need to implement a bypass for this webhook in cases where we are doing adoptions and have independently verified the contents of the databases. But without any kind of validation, we should block users from inadvertently causing potentially unrecoverable errors.
> Block changing DatabaseInstance

- config/rbac/role.yaml
- controllers/heat_controller.go
- go.mod
- go.sum
- tests/functional/heat_controller_test.go
- tests/kuttl/common/assert-sample-deployment.yaml
This change bumps the mariadb-operator version and fixed envtest
> Bump mariadb-operator version

- config/manifests/bases/heat-operator.clusterserviceversion.yaml
recent changes did not update the CSV yaml file
> update CSV for TLS and fips

- README.md
- config/samples/heat_v1beta1_heatapi.yaml
- config/samples/heat_v1beta1_heatapicfn.yaml
- config/samples/heat_v1beta1_heatengine.yaml
The field was removed in 316002f57425671e53f2512be1cfe8512cc169dd
JIRA: https://issues.redhat.com/browse/OSPRH-7867
> Removing documentation and sample references to the database field of PasswordSelectors struct

- config/manifests/bases/heat-operator.clusterserviceversion.yaml
This change adds the required OpenShift annotations
Resolves: https://issues.redhat.com/browse/OSPRH-7943
> Add OpenShift annotations

- config/rbac/role.yaml
- controllers/heat_controller.go
- controllers/heatapi_controller.go
- controllers/heatcfnapi_controller.go
- controllers/heatengine_controller.go
We also took the opportunity and added patch to all the existing rbac rules that had update already to avoid similar issues in the future
Resolves: https://issues.redhat.com/browse/OSPRH-8363
> Adding patch rbac perm for serviceaccounts

- config/manifests/bases/heat-operator.clusterserviceversion.yaml
Jira: https://issues.redhat.com/browse/OSPRH-8222
> Drop Icon field

- controllers/heat_controller.go
- controllers/heat_controller_test.go
- zuul.d/jobs.yaml
internal endpoint was being overwritten by the public one
> Fix vhost configuration

- pkg/heatapi/deployment.go
- pkg/heatcfnapi/deployment.go
This change switches to using the healthcheck endpoints: https://github.com/openstack/heat/blob/master/etc/heat/api-paste.ini
Jira: https://issues.redhat.com/browse/OSPRH-13796
> Use healthcheck endpoint for probes

- pkg/heat/const.go
- pkg/heat/funcs.go
- pkg/heatapi/deployment.go
- pkg/heatcfnapi/deployment.go
- pkg/heatengine/deployment.go
This change cleans up how probes are defined and deduplicates the logic
> Dedup probe logic

- templates/heat/config/00-default.conf
Jira: [OSPRH-16651](https://issues.redhat.com//browse/OSPRH-16651)
> Fix memcache_sasl_enable parameter to be memcache_sasl_enabled

- OWNERS_ALIASES
Signed-off-by: James Slagle <jslagle@redhat.com>
> Remove bshephard
